name: Notify about release
on:
  release:
    types:
      - published
jobs:
  telegram:
    name: Send Telegram notification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Send a Telegram notification
        uses: ./.github/actions/telegram-send-message
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          chat_id: "@amodeus_app"
          text: >
            <b>A new version <i>${{ github.event.release.tag_name }}</i> of <i>${{ github.repository }}</i> has just
            been released!</b>


            You can view full changelog and downloads at
            <a href="${{ github.server_url }}/${{ github.repository }}/releases/${{ github.event.release.tag_name }}">GitHub</a>.
          parse_mode: HTML
